"""initial multi-channel multi-niche schema

Revision ID: 260173816f1b
Revises: 
Create Date: 2026-06-22 16:19:47.113303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260173816f1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('generator_key', sa.String(length=64), nullable=False),
    sa.Column('made_for_kids_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niches_slug'), 'niches', ['slug'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=True),
    sa.Column('oauth_credentials_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', name='channelstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_channels_youtube_channel_id'), 'competitor_channels', ['youtube_channel_id'], unique=True)
    op.create_table('title_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=False),
    sa.Column('total_watch_hours', sa.Float(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_ypp_eligible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_channel_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_channel_id'], ['competitor_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_videos_youtube_video_id'), 'competitor_videos', ['youtube_video_id'], unique=True)
    op.create_table('video_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('idea', 'researching', 'rendering', 'review', 'scheduled', 'published', 'failed', name='videoprojectstatus'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('audio_asset_path', sa.String(length=512), nullable=True),
    sa.Column('visual_asset_path', sa.String(length=512), nullable=True),
    sa.Column('render_output_path', sa.String(length=512), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=64), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_projects')
    op.drop_index(op.f('ix_competitor_videos_youtube_video_id'), table_name='competitor_videos')
    op.drop_table('competitor_videos')
    op.drop_table('channel_metrics')
    op.drop_table('title_templates')
    op.drop_index(op.f('ix_competitor_channels_youtube_channel_id'), table_name='competitor_channels')
    op.drop_table('competitor_channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_niches_slug'), table_name='niches')
    op.drop_table('niches')
    # ### end Alembic commands ###
